CREATE TABLE Customers(
	CustomerId int NOT NULL PRIMARY KEY,
	LastName VARCHAR(256) NOT NULL,
	FirstName VARCHAR(256) NOT NULL,
	StreeAddress NVARCHAR(256) NOT NULL,
	City VARCHAR(256) NOT NULL,
	Country VARCHAR(256) NOT NULL,
	PhoneNumber NVARCHAR(13) NOT NULL
)